In [31]:
transactions = [
    {"id": 1, "product": "Laptop", "price": 1200, "quantity": 2, "region": "EU"},
    {"id": 2, "product": "Phone", "price": 800, "quantity": -1, "region": "US"},
    {"id": 3, "product": "Tablet", "price": 0, "quantity": 5, "region": "EU"},
    {"id": 4, "product": "Monitor", "price": 350, "quantity": 3, "region": "US"},
    {"id": 5, "product": "Laptop", "price": 1200, "quantity": 1, "region": "EU"},
    {"id": 6, "product": "Keyboard", "price": 75, "quantity": 10, "region": "APAC"},
]


In [32]:
#part a

In [33]:
valid_transactions = []
for transaction in transactions: 
    if transaction["price"] > 0 and transaction["quantity"] >= 0: 
        valid_transactions.append(transaction)
for i in valid_transactions:
    print(i)

{'id': 1, 'product': 'Laptop', 'price': 1200, 'quantity': 2, 'region': 'EU'}
{'id': 4, 'product': 'Monitor', 'price': 350, 'quantity': 3, 'region': 'US'}
{'id': 5, 'product': 'Laptop', 'price': 1200, 'quantity': 1, 'region': 'EU'}
{'id': 6, 'product': 'Keyboard', 'price': 75, 'quantity': 10, 'region': 'APAC'}


In [34]:
#part b

In [35]:
for total in valid_transactions:
    total["total"] = total["price"] * total["quantity"]
print(valid_transactions)

[{'id': 1, 'product': 'Laptop', 'price': 1200, 'quantity': 2, 'region': 'EU', 'total': 2400}, {'id': 4, 'product': 'Monitor', 'price': 350, 'quantity': 3, 'region': 'US', 'total': 1050}, {'id': 5, 'product': 'Laptop', 'price': 1200, 'quantity': 1, 'region': 'EU', 'total': 1200}, {'id': 6, 'product': 'Keyboard', 'price': 75, 'quantity': 10, 'region': 'APAC', 'total': 750}]


In [36]:
#part c

In [37]:
revenue_per_region = {}
for region in valid_transactions:
    if region["region"] in revenue_per_region: 
        revenue_per_region[region["region"]] += region["total"]
    else:
        revenue_per_region[region["region"]] = region["total"]
print(revenue_per_region)


{'EU': 3600, 'US': 1050, 'APAC': 750}


In [38]:
#part d

In [39]:
top_region = max(revenue_per_region, key=Revenue_per_region.get)
print(f"Highest total revenue: {top_region} = {Revenue_per_region[top_region]}")

Highest total revenue: EU = 3600


In [ ]:
#task 2

In [37]:
sales = [1200, 980, 1540, 870, 2010, 1650, 1300, 1100, 950, 1780, 2200, 1430, 1600, 1900]

#function

def summarise_sales(saleslist):
    total = sum(saleslist)
    average = round(total/len(saleslist),2)
    best_day = saleslist.index(max(saleslist)) + 1
    worst_day = saleslist.index(min(saleslist)) + 1
    above_average_count = 0
    for day in saleslist: 
        if day > average:
            above_average_count += 1

#dictionary

    return{
        "total": total,
        "average": average,
        "best_day": best_day,
        "worst_day": worst_day,
        "above_average_count": above_average_count
}

print(summarise_sales(sales))

{'total': 20510, 'average': 1465.0, 'best_day': 11, 'worst_day': 4, 'above_average_count': 7}


In [ ]:
#task 3

In [39]:
students = [
    {"name": "Anna", "grade": 85, "attendance": 0.92},
    {"name": "Erik", "grade": 58, "attendance": 0.75},
    {"name": "Mia", "grade": 91, "attendance": 0.98},
    {"name": "Leo", "grade": 44, "attendance": 0.60},
    {"name": "Sara", "grade": 72, "attendance": 0.88},
    {"name": "Tom", "grade": 67, "attendance": 0.70},
    {"name": "Nina", "grade": 95, "attendance": 0.99},
    {"name": "Olli", "grade": 50, "attendance": 0.65},
]



In [40]:
#part a

In [41]:
passing = []
for student in students:
    if student["grade"] >= 50:
        passing.append(student["name"])

print(passing)

['Anna', 'Erik', 'Mia', 'Sara', 'Tom', 'Nina', 'Olli']


In [ ]:
#part b

In [43]:
for student in students:
    if student["grade"] >= 80:
        print(f"{student['name']}: Excellent")
    elif student["grade"] >= 50:
        print(f"{student['name']}: Pass")
    else:
        print(f"{student['name']}: Fail")

Anna: Excellent
Erik: Pass
Mia: Excellent
Leo: Fail
Sara: Pass
Tom: Pass
Nina: Excellent
Olli: Pass


In [ ]:
#part c

In [45]:
count = 0
for attendance in students:
    if attendance["attendance"] < 0.80:
        count += 1

print(count)

4


In [ ]:
#part d

In [56]:
top_grade = 0
top_student = None

for student in students: 
    if student["grade"] > top_grade:
        top_grade = student["grade"]
        top_student = student["name"]

print(f"{top_student}:{top_grade}")


Nina:95


In [ ]:
#part e

In [60]:
top = max(students, key=lambda student: student["grade"])

print(f"{top["name"]}: {top["grade"]}") 

Nina: 95


In [ ]:
#task 4

In [21]:
class Portfolio:
    def __init__(self, owner):
        self.owner = owner
        self.holdings = {}  # ticker -> {shares, price_per_share}
#task a
    def add_asset(self, ticker, shares, price_per_share):
        if ticker in self.holdings:
            self.holdings[ticker]["shares"] += shares
            self.holdings[ticker]["price_per_share"] = price_per_share
        else:
            self.holdings[ticker] = {"shares": shares, "price_per_share": price_per_share}

#task b
    def total_value(self):
        total = 0
        for ticker in self.holdings:
            total += self.holdings[ticker]["shares"] * self.holdings[ticker]["price_per_share"]
        return total

#task c
    def most_valuable(self):
        return max(self.holdings, key = lambda ticker : self.holdings[ticker]["shares"] * self.holdings[ticker]["price_per_share"])

#task d
    def __str__(self):
        return f" Owner: {self.owner}, assets = {len(self.holdings)}, total value = {self.total_value()}"
            

my_portfolio = Portfolio("John") 

my_portfolio.add_asset("AAPL", 10, 150)
my_portfolio.add_asset("TSLA", 5, 200)
my_portfolio.add_asset("NVDA", 8, 300)

print(my_portfolio.total_value())
print(my_portfolio.most_valuable())
print(my_portfolio)

4900
NVDA
 Owner: John, assets = 3, total value = 4900


In [ ]:
#task 5

In [6]:
orders = [
    ("2025-01-15", "Laptop"), ("2025-01-22", "Phone"),
    ("2025-02-03", "Laptop"), ("2025-02-14", "Tablet"),
    ("2025-03-01", "Phone"), ("2025-03-10", "Phone"),
    ("2025-03-22", "Laptop"), ("2025-04-05", "Monitor"),
]

from datetime import date
dates = []
for order in orders:
    dates.append(date.fromisoformat(order[0]))
        
    difference = max(dates) - min(dates)
print(difference)

80 days, 0:00:00


In [ ]:
#task 6

In [11]:
import numpy as np

# Rows: years (2022, 2023, 2024), Columns: quarters (Q1, Q2, Q3, Q4)
revenue = np.array([
    [210, 230, 190, 250],
    [220, 260, 200, 270],
    [250, 290, 230, 310]])

#part a

print(revenue.sum(axis=1))

#part b

print(revenue.mean(axis=0))

#part c

print(revenue[2] * np.array([1.05, 1.03, 1.08, 1.02]))

#part d

print(revenue[revenue > 250])

[ 880  950 1080]
[226.66666667 260.         206.66666667 276.66666667]
[262.5 298.7 248.4 316.2]
[260 270 290 310]


In [ ]:
#task 7

In [14]:
import pandas as pd

data = {
    "employee": ["Anna", "Erik", "Mia", "Leo", "Sara", "Tom"],
    "department": ["Finance", "Marketing", "Finance", "IT", "Marketing", "IT"],
    "salary": [4500, 4000, 4800, 5200, 3900, 5100],
    "years_exp": [5, 3, 7, 10, 2, 8],
    "performance_score": [4.2, 3.8, 4.5, 4.0, 3.5, 4.9]
}

df = pd.DataFrame(data)

#part a

df["salary_per_year_exp"] = round(df["salary"] / df["years_exp"])

#part b

print(df.sort_values("performance_score", ascending=False).head(3))

#part c

print(df.loc[(df["department"] == "Finance") & (df["performance_score"] > 4.0)])

#part d

df = df.rename(columns={"years_exp": "experience_years"})
print(df)

#part e

print(df.iloc[0:4, [2, 4]])


  employee department  salary  years_exp  performance_score  \
5      Tom         IT    5100          8                4.9   
2      Mia    Finance    4800          7                4.5   
0     Anna    Finance    4500          5                4.2   

   salary_per_year_exp  
5                638.0  
2                686.0  
0                900.0  
  employee department  salary  years_exp  performance_score  \
0     Anna    Finance    4500          5                4.2   
2      Mia    Finance    4800          7                4.5   

   salary_per_year_exp  
0                900.0  
2                686.0  
  employee department  salary  experience_years  performance_score  \
0     Anna    Finance    4500                 5                4.2   
1     Erik  Marketing    4000                 3                3.8   
2      Mia    Finance    4800                 7                4.5   
3      Leo         IT    5200                10                4.0   
4     Sara  Marketing    3900   

In [ ]:
#task 8

In [17]:
import numpy as np
import pandas as pd

rng = np.random.default_rng(seed=123)
days = pd.date_range(start="2025-01-06", periods=28, freq="D")
visitors = rng.integers(200, 600, size=28)
conversion_rate = rng.uniform(0.02, 0.08, size=28).round(4)
avg_order_value = rng.normal(50, 10, size=28).round(2)

#part a

df = pd.DataFrame({
    "date": days,
    "visitors": visitors,
    "conversion_rate": conversion_rate,
    "avg_order_value": avg_order_value
})

df = df.set_index("date")

#part b

df["conversions"] = round(df["visitors"] * df["conversion_rate"])

df["daily_revenue"] = df["conversions"] * df["avg_order_value"]


print(df)

            visitors  conversion_rate  avg_order_value  conversions  \
date                                                                  
2025-01-06       206           0.0645            64.30         13.0   
2025-01-07       472           0.0578            48.44         27.0   
2025-01-08       437           0.0756            43.26         33.0   
2025-01-09       221           0.0339            43.61          7.0   
2025-01-10       563           0.0679            49.39         38.0   
2025-01-11       288           0.0511            46.07         15.0   
2025-01-12       302           0.0339            72.90         10.0   
2025-01-13       273           0.0300            42.82          8.0   
2025-01-14       333           0.0499            50.33         17.0   
2025-01-15       270           0.0550            50.28         15.0   
2025-01-16       339           0.0311            50.28         11.0   
2025-01-17       524           0.0209            50.55         11.0   
2025-0